version: '3.9'

services:
  postgres:
    image: postgres:17-alpine
    container_name: nestjs-first-api-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: nestjs_first_api_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - nestjs-network
    labels:
      com.nestjs-first-api.service: 'database'
      com.nestjs-first-api.env: 'development'

volumes:
  postgres_data:
    name: nestjs-first-api-postgres-data

networks:
  nestjs-network:
    name: nestjs-first-api-network
    driver: bridge
