name: publish

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  create-docker-image:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PA_TOKEN }}

      - name: Build image
        run: |
          docker build . --tag ghcr.io/luirrodev/nestjs-first-api:latest
          docker push ghcr.io/luirrodev/nestjs-first-api:latest
